import { ISLANDS } from "./islands";
import type { GameStrings } from "./types";

export const en: GameStrings = {
  islands: ISLANDS.map((i) => i.en),
  deaths: [
    "It bit you! The Red Cross recommends: wash the wound with plenty of water and soap.",
    "ELKETHE clarifies: the incident is not confirmed.",
    "You went viral on TikTok. #lagokefalos #fyp",
    "WWF states: “The media made a mountain out of a molehill.”",
    "The fishermen warned you. You didn't listen.",
    "A parliamentary committee will investigate the incident. In 4-5 years.",
    "Your Aegean pasture has been seized by the European Prosecutor.",
  ],
  biteQuips: [
    "OUCH! It bit me!",
    "The pain! 😵",
    "I'm reporting this to ELKETHE!",
    "Call the Red Cross!",
    "Mamáaa!",
    "Dude, I just ate!",
    "The incident is CONFIRMED!",
    "This wasn't in the holiday package!",
    "I'm reporting you to the European Prosecutor!",
    "This fish is declared under three tax IDs!",
  ],
  idleQuips: [
    "Nice little swim...",
    "€5.33 a kilo, I'll get rich! 💰",
    "Where's my freddo? ☕",
    "This goes straight to TikTok 📱",
    "Still beats a 9-to-5",
    "The sea was quiet... too quiet",
    "The fishermen were right after all",
    "New job title: lagokefalos hunter",
    "The Ministry is proud of me 🇬🇷",
    "Think it'll bite me? ...Think so?",
    "I'll declare the sea as pasture to OPEKEPE 🐐",
    "Declared the lagokefaloi as livestock",
    "Looking for the big fish of the case file 🐟",
    "Bananas on Olympus, lagokefaloi in the Aegean",
    "Farmer by declaration, jet-skier by trade",
    "The inquiry committee is the best reality show",
    "Collecting subsidies, seeing no fish",
    "Shhh... someone's wiretapping us 📞",
  ],
  hud: {
    rate: "€5.33/kg",
    invincible: "INVINCIBLE",
    pose: "selfie",
    hintTouch: "Drag your finger ← →",
    hintKeys: "← → arrows or click",
  },
  popups: {
    caught: (kg, eur) => `+${kg}kg = €${eur}`,
    smashed: (kg, eur) => `💥 +${kg}kg = €${eur}`,
    speedUp: "+ speed!",
    freddo: "☕ CAFFEINE! Invincible 3″!",
    souvlakiLife: "🥙 +1 life!",
    souvlakiFull: "🥙 +2kg (stuffed)",
    net: "🕸 Net ×2!",
    cam: "📱 Stopped for a selfie!",
    frappe: (kg, eur) => `🥤 FRAPPÉ FRENZY! +${kg}kg = €${eur}`,
    frappeEmpty: "🥤 FRAPPÉ! The sea is cleared",
  },
  ui: {
    presents: "The Ministry of Rural Development presents*",
    title: "LAGOKEFALOS",
    subtitle: "THE BOUNTY",
    bounty: "💰 Reward: €5.33 / kilo",
    howTo1: "Dodge the big lagokefaloi 🐡",
    howTo2: "Grab the small ones for the bounty 💶",
    howTo3: "Drag ← → to change lane",
    howToCollect: "COLLECT",
    howToCollectSub: "small = €5.33/kg",
    howToAvoid: "AVOID",
    howToAvoidSub: "big = they bite!",
    play: "START",
    daily: "🗓 Daily challenge (same sea for everyone)",
    bestPrefix: (eur, kg) => `Your best: €${eur} (${kg}kg)`,
    parody:
      "*Parody. The lagokefalos is not edible. The leaderboard is public — your name will be visible to other players.",
    receipt: "Official Bounty Receipt",
    haulLine: (kg) => `${kg} kg of lagokefalos delivered`,
    islandLine: (island) => `You reached: ${island}`,
    rankLine: (rank) => `🏅 Rank #${rank} in the Global Treasury`,
    namePlaceholder: "Your name...",
    again: "AGAIN!",
    share: "📣 Share it",
    board: "🏆 Global Treasury",
    boardEmpty: "Nobody yet — be the first!",
    boardOffline: "The treasury is closed (offline).",
    boardLoading: "Loading...",
    shareText: (kg, eur) =>
      `I caught ${kg}kg of lagokefalos = €${eur} from the Greek state 💰🐡 Can you beat me?`,
    shareCopied: "Copied! 📋 Paste it on Instagram/WhatsApp/TikTok.",
    shareManual: "Copy it manually:",
    langToggle: "ΕΛ",
  },
};
